codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "60...80"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/test_*.py"