name: OpenAI PR Description Generator

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment: prep
    steps:
      - uses: actions/checkout@v3
      - name: Generate PR description
        id: generate-pr-description
        uses: Ant0wan/openai-pr@v1
        with:
          model: 'gpt-4'
          api-key: ${{ secrets.OPENAI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}